# Generated by Django 4.1.1 on 2022-10-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user'},
        ),
    ]
