# Generated by Django 4.1.1 on 2022-12-03 14:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_companyprofile_description_companyprofile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="DZ"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="DZ"
            ),
        ),
    ]
