# Generated by Django 4.1.1 on 2022-12-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_companyprofile_phone_employeeprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
