# Generated by Django 4.1.1 on 2022-10-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
