# Generated by Django 4.1.1 on 2022-12-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_companyprofile_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="rating",
            field=models.ManyToManyField(
                related_name="rated_companies", to="accounts.employeeprofile"
            ),
        ),
    ]
