# Generated by Django 4.1.1 on 2022-12-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_companyprofile_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="rating",
        ),
        migrations.CreateModel(
            name="CompanyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.PositiveIntegerField(default=1)),
                (
                    "rated_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="accounts.companyprofile",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rated_companies",
                        to="accounts.employeeprofile",
                    ),
                ),
            ],
        ),
    ]
