# Generated by Django 4.1.1 on 2022-12-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_companyprofile_rating_companyrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
