# Generated by Django 4.1.1 on 2022-10-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_description_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
