# Generated by Django 4.1.1 on 2022-12-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_location_user"),
        ("accounts", "0009_companyprofile_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="locations.location",
            ),
        ),
    ]
