# Generated by Django 4.1.1 on 2022-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('COMPANY', 'Company')], default='EMPLOYEE', max_length=100),
        ),
    ]
