# Generated by Django 4.1.1 on 2023-01-03 10:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_employeeprofile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="cover",
            field=models.ImageField(
                default="", upload_to=accounts.models.coverFileNamer
            ),
            preserve_default=False,
        ),
    ]
