# Generated by Django 4.1.1 on 2022-10-21 18:33

import accounts.models
import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('accounts', '0013_rename_employee_employeeprofile_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='location',
            field=models.ForeignKey(default=15, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='cv',
            field=models.FileField(null=True, upload_to=accounts.models.cvFileNamer, validators=[accounts.validators.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to=accounts.models.imageFileNamer)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number_of_employees', models.PositiveIntegerField(default=1)),
                ('location', models.ForeignKey(default=15, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='locations.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
