locations = [{'id': 1, 'name': "Adrar"},
             {'id': 2, 'name': "Chlef"},
             {'id': 3, 'name': "Laghouat"},
             {'id': 4, 'name': "Oum El Bouaghi"},
             {'id': 5, 'name': "Batna"},
             {'id': 6, 'name': "Bejaia"},
             {'id': 7, 'name': "Biskra"},
             {'id': 8, 'name': "Bechar"},
             {'id': 9, 'name':"Blida"},
             {'id': 10, 'name':"Bouira"},
             {'id': 11, 'name':"Tamanrasset"},
             {'id': 12, 'name':"Tebessa"},
             {'id': 13, 'name':"Tlemcen"},
             {'id': 14, 'name':"Tiaret"},
             {'id': 15, 'name':"Tizi Ouzou"},
             {'id': 16, 'name':"Alger"},
             {'id': 17, 'name':"Djelfa"},
             {'id': 18, 'name':"Jijel"},
             {'id': 19, 'name':"Setif"},
             {'id': 20, 'name':"Saida"},
             {'id': 21, 'name':"Skikda"},
             {'id': 22, 'name': "Sidi Bel Abbes"},
             {'id': 23, 'name': "Annaba"},
             {'id': 24, 'name': "Guelma"},
             {'id': 25, 'name': "Constantine"},
             {'id': 26, 'name': "Medea"},
             {'id': 27, 'name': "Mostaganem"},
             {'id': 28, 'name': "'M'Sila"},
             {'id': 29, 'name': "Mascara"},
             {'id': 30, 'name': "Ouargla"},
             {'id': 31, 'name': "Oran"},
             {'id': 32, 'name': "El Bayadh"},
             {'id': 33, 'name': "Illizi"},
             {'id': 34, 'name': "Bordj Bou Arreridj"},
             {'id': 35, 'name': "Boumerdès"},
             {'id': 36, 'name': "El Tarf"},
             {'id': 37, 'name': "Tindouf"},
             {'id': 38, 'name': "Tissemsilt"},
             {'id': 39, 'name': "El Oued"}
             ]
