# Generated by Django 4.1.1 on 2023-01-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("-created", "-updated")},
        ),
        migrations.AddField(
            model_name="review",
            name="helpful_with_no",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="helpful_with_yes",
            field=models.IntegerField(default=0),
        ),
    ]
