# Generated by Django 4.1.1 on 2022-10-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('positions', models.IntegerField(default=1)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
