# Generated by Django 4.1.1 on 2022-11-04 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_location_job_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
