# Generated by Django 4.1.1 on 2022-10-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='introduction',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
