# Generated by Django 4.1.1 on 2022-12-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_location_user"),
        ("jobs", "0006_alter_job_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="locations.location",
            ),
        ),
    ]
