# Generated by Django 4.1.1 on 2022-12-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_location_user"),
        ("jobs", "0007_alter_job_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ("-created", "-update")},
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="locations.location",
            ),
        ),
    ]
