# Generated by Django 4.1.4 on 2022-12-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_location_user"),
        ("accounts", "0011_alter_employeeprofile_location"),
        ("jobs", "0008_alter_job_options_alter_job_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="accounts.companyprofile",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="introduction",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="positions",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.IntegerField(blank=True, verbose_name="monthly salary"),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
