# Generated by Django 4.1.1 on 2022-10-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('jobs', '0011_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='locations.location'),
        ),
    ]
